// Generated by CoffeeScript 1.6.3
(function() {
  var Showoff, express, fs, spawn;

  fs = require("fs");

  spawn = require('child_process').spawn;

  express = require("express");

  Showoff = (function() {
    function Showoff() {}

    Showoff.prototype.run = function(options) {
      var app, cwd, port, publicDir;
      if (options == null) {
        options = {};
      }
      port = options.port || 8080;
      app = express();
      cwd = process.cwd();
      publicDir = cwd + "/public";
      return fs.exists(publicDir, function(exists) {
        if (!exists) {
          publicDir = process.cwd();
        }
        app.use(express["static"](publicDir));
        return app.listen(port, function() {
          var host;
          host = "http://127.0.0.1:" + port;
          console.log("Showing off on " + host);
          if (options.open) {
            return spawn('open', [host]);
          }
        });
      });
    };

    return Showoff;

  })();

  module.exports = new Showoff;

}).call(this);
