// Generated by CoffeeScript 1.6.3
(function() {
  var Showoff, express, fs;

  fs = require("fs");

  express = require("express");

  Showoff = (function() {
    function Showoff() {}

    Showoff.prototype.run = function(options) {
      var app, cwd, port, publicDir;
      if (options == null) {
        options = {};
      }
      port = options.port || 8080;
      app = express();
      cwd = process.cwd();
      publicDir = cwd + "/public";
      return fs.exists(publicDir, function(exists) {
        if (!exists) {
          publicDir = process.cwd();
        }
        app.use(express["static"](publicDir));
        return app.listen(port, function() {
          return console.log("Showing off on 127.0.0.1:" + port);
        });
      });
    };

    return Showoff;

  })();

  module.exports = new Showoff;

}).call(this);
